---
sidebar: sidebar_aws
permalink: aws/reference_whats_new_cloud_volumes_aws.html
keywords: Cloud Volumes Service for AWS, what's new, features, enhancements
summary: NetApp periodically updates Cloud Volumes Service for AWS to bring you new features and enhancements.
---

= What's new in Cloud Volumes Service for AWS
:toc: macro
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp periodically updates Cloud Volumes Service for AWS to bring you new features and enhancements.

== February 2021

* A new Cloud Volumes API (`PerformanceMetrics`) is now available to retrieve performance statistics including IOPS, Bandwidth, and Latency.  To learn more, see link:reference_cloud_volume_apis.html[Cloud Volumes APIs^].

== July 2020
* The Cloud Volumes Service now supports wider RFC 1918 private network ranges between /16 and /28. Previously only /28 ranges where supported.
* The 'Sync' feature now integrates directly with the Cloud Sync UI to provide increased functionality.
* Volumes can be converted to and from NSFv3, NFSv4.1, and both NFSv3 and NFSv4.1 via API calls.
* The API examples and sample Python scripts have been updated to the v2 API. link:reference_cloud_volume_apis.html[See Cloud Volumes APIs].
* ACLs are now enabled for NFSv4.1 volumes.
* The Cloud Volumes Service is now certified with SOC 2 type 1.
* The Cloud Volumes Service is now available in Singapore (ap-southeast-1).

== March 2020
* Cloud Volumes Service now supports a maximum I/O size of 1 MiB for NFSv3 and NFSv4.1 mounts. Previously the maximum I/O size was 64 KiB. Increasing the I/O size may improve performance for some workloads.
To increase the I/O size, use the mount options "rsize" and/or "wsize", for example:
`mount -o nfsvers=4.1,rsize=1048576,wsize=1048576 172.25.0.4:/vol1 /mnt/cv`

== February 2020
* Cloud Volumes Service is now available as a Metered (pay as you go) subscription in the AWS Marketplace. See the Marketplace listing for more details at: https://aws.amazon.com/marketplace/pp/B0848MXK74
Note that the original monthly and annual subscription plans are still available.

== January 2020
* Cloud Volumes Service now supports SMB multichannel which uses multiple network connections simultaneously to provide increased performance. Multichannel is enabled by default on Windows clients, but requires that the EC2 instance uses a network adapter that support RSS (Receive Side Scaling).
* Reverting a volume from a snapshot is now available from the Cloud Volumes Service user interface. This enables you to revert volumes to a point in time snapshot without requiring clients to remount. See link:task_reverting_volume_to_snapshot.html[Reverting a volume from a snapshot] for details.
