---
sidebar: sidebar_aws
permalink: aws/reference_whats_new_cloud_volumes_aws.html
keywords: Cloud Volumes Service for AWS, what's new, features, enhancements
summary: NetApp periodically updates Cloud Volumes Service for AWS to bring you new features and enhancements.
---

= What's new in Cloud Volumes Service for AWS
:toc: macro
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp periodically updates Cloud Volumes Service for AWS to bring you new features and enhancements.

== July 2020
* The Cloud Volumes Service now supports wider RFC 1918 private network ranges between /16 and /28. Previously only /28 ranges where supported.
* The 'Sync' feature now integrates directly with the Cloud Sync UI to provide increased functionality.
* Volumes can be converted to and from NSFv3, NFSv4.1, and both NFSv3 and NFSv4.1 via API calls.
* ACLs are now enabled for NFSv4.1 volumes.
* The Cloud Volumes Service is now certified with SOC 2 type 1.
* The Cloud Volumes Service is now available in Singapore (ap-southeast-1).

== March 2020
* Cloud Volumes Service now supports a maximum I/O size of 1 MiB for NFSv3 and NFSv4.1 mounts. Previously the maximum I/O size was 64 KiB. Increasing the I/O size may improve performance for some workloads.
To increase the I/O size, use the mount options "rsize" and/or "wsize", for example:
`mount -o nfsvers=4.1,rsize=1048576,wsize=1048576 172.25.0.4:/vol1 /mnt/cv`

== February 2020
* Cloud Volumes Service is now available as a Metered (pay as you go) subscription in the AWS Marketplace. See the Marketplace listing for more details at: https://aws.amazon.com/marketplace/pp/B0848MXK74
Note that the original monthly and annual subscription plans are still available.

== January 2020
* Cloud Volumes Service now supports SMB multichannel which uses multiple network connections simultaneously to provide increased performance. Multichannel is enabled by default on Windows clients, but requires that the EC2 instance uses a network adapter that support RSS (Receive Side Scaling).
* Reverting a volume from a snapshot is now available from the Cloud Volumes Service user interface. This enables you to revert volumes to a point in time snapshot without requiring clients to remount. See link:task_reverting_volume_to_snapshot.html[Reverting a volume from a snapshot] for details.

== December 2019
* Cloud Volumes Service now supports NFSv4.1 in addition to NFSv3 and SMB. A volume can be exported over any or all of the supported protocols. NFSv4.1 is a stateful protocol and provides improved file locking, ACLs for better compatibility between Linux and Windows, and many other improvements.
* Cloud Volumes can be configured so that the .snapshot directory (previous version in Windows) can be hidden or shown.
* An Overview page is now available per volume that displays QoS settings, data usage, and performance information such as bandwidth, IOPS, and latency.

== September 2019
* Cloud Volumes Service now supports up to 100 million files per volume. The maximum file count is increased by 20 million for each Terabyte allocated up to 100 million. The maximum may be increased to higher than 100 million via a customer support request.
* Cloud volume names now support up to 253 characters; an increase from the previous limit of 64 characters.
*	The user interface now displays the service level per volume in the volume list page.

== August 2019
* Cloud Volumes Service now provides up to 4,500 MB/s, instead of 3,500 MB/s, at certain capacity levels. See link:reference_selecting_service_level_and_quota.html#cost-comparison-for-service-levels-and-allocated-capacity[Selecting the service level and the allocated capacity] for details.
* Added API examples and sample Python scripts for Active Directory functions:  link:reference_cloud_volume_apis.html[Cloud Volumes APIs].

== July 2019
* Creating a volume from a snapshot is now rapid, and the volume is available within seconds regardless of the amount of data in the parent volume.
* The user interface now displays the used capacity per volume.
* The API has been updated to report used capacity, and total inodes and used inodes.
* The API has been updated to use the same service levels names as the user interface (Standard, Premium, and Extreme).
* The sample Python scripts have been updated to match the updated APIs.
